### ISSUE TITLE
2021-07-13 ~ Response to message from Peter Donovan 

### ISSUE THREAD

**Issue by theo-armour** [theo-armour/maps-2021#1]
@managingwholes

![image](https://user-images.githubusercontent.com/547626/125688752-4cae2194-c669-4c91-be79-d132e84e013e.png)

[US Crop Insurance Indemnities by County 1979-2017  ~ 2021-07-11]( https://theo-armour.github.io/maps-2021/sandbox/globe-us-county-indemnity/v-2021-07-11/globe-us-county-indemnity.html )

This is a reply to a personal email sent by Peter Donovan to me regarding the above project. Peter's text - quoted below - has been edited 

## Time

>>Sorry for my slow response, still catching up from the 2-month road trip with writing and so on.

Let us communicate via emails and issues. Let us keep time as less of necessary thing than simply good thoughts.

## Snazziness
>> I am realizing that what is needed, what I am looking for, is not snazzier displays, but more context and user control. 

In my efforts, I think snazzy is an accident. ;-) What drives me are the attempts to display a number of variables interacting simultaneously - using color, quantity, shape, sound, position and whatever. My mission is to get a bunch of PhDs with very deep knowledge of a topic to gasp "Wow, I've never seems these parameters in that way". To paraphrase Immanuel Kant sort of: new knowledge is a perception more than an intuition - ie, if you can: hit 'em between the eyeballs.

## Relevant data

>> The technology we have makes it easy and tempting to add less-than-relevant data, context, and displays. **The purpose of the crop insurance map is to enable the user to locate their neighborhood and see the situation and change over time.**

Bingo! And this can (will?) happen!

## Context
>>Better context might be number of cropland acres in the county. Population or 3D effects seem extraneous.

Yes! And where are the cropland acres statistics kept?

## Bandwidth 
>> I still think bandwidth is an issue which is why I use topojson for this. I live and work with people in rural counties where connection speeds are very different from what you probably have.

I differentiate between the stages of designing future software and building production software. In my world, you "design" for the future and "build" for the past. So for now "go for broke" while we design for the future - then later we may "polyfill up the wazoo".

two other things

1. [Fast broadband for all]( https://www.broadbandcommission.org/ ) is a United Nations Sustainable Development Goal for 2030
 
2. Have a look at this globe:

https://pushme-pullyou.github.io/tootoo-2021/cookbook-threejs/glc-globe-csv-population/

This globe displays data for 26,000 places all at once. I could not imagine doing this two or three years ago.

## Colors versus sticks

>> For this data set, a color palette is probably better than the sticks, and easier to have a tooltip on mouseover when pointer is in the county, not only on the stick. (Low or zero values are hard to find.) 

For sure colors are better when you need to display a single variable per county. But, say, you would like to display two variables per county - or more?

Have a look at: https://theo-armour.github.io/maps-2021/sandbox/us-county-votes/

You can see Republican and Democrat votes and an indicator of flips - three statistics. Plus there is an indicate of importance - changing colors gives little a limited vision - and even a vision that big counties are more important than little counties.

So here, don't we want - maybe? - somehow to compare corn, wheat, soybean, cotton, rize and more along with rainfall, maintenance and more?

## Time
>>I like your idea of a slider for the animation, so user can go to a particular year, go back and forth, etc.

And animating the display of the years would be good too. 

## County Charts
>>It would be good to display county data for 1979-present in a chart in a popup on click. This could probably be done with the existing d3 framework?

next release

## Data Sets
>>RMA data needs lots of munging, realtime data retrieval would not be possible. Their website is much changed since my last visit. The data sets I use are from https://www.rma.usda.gov/en/Information-Tools/Summary-of-Business/Cause-of-Loss and I need to update.

Uncle Sam, why must you complicate things so?

## Crop Insurance Page
>> It's been helpful to think this through, and I am realizing also that the whole page here, https://soilcarboncoalition.org/crop-insurance/
 needs a major work over with much better context for understanding the data. The EWG maps (https://www.ewg.org/research/crop-insurance-lottery) are pretty well done I thought. I'm sure they're using ARCGIS and they have way too much detail on the coastlines . . . 

Why not just capture the ARCGIS into PNG files and show those? In any case., this page will be a lot more fun when we bash our heads together some more. 
  
## Zip Codes of Revelations
The 2009 ERS atlas effort was not repeated for some reason, too revealing perhaps .. . .  The EWG folks have a database of Farm Bill payments by zip code of recipient, which is not necessarily where the farm is. 

lol

## Context, Direction, Complexity
>> The whole issue of context, what to include, what not to include ... it's complex, and purpose needs better explanation. I apologize for the misdirection: what this kind of thing requires is not necessarily a better or different technical presentation, but better context--yet another job for yours truly I guess. 

Yes! I'm all ears. And looking for fun stuff to do!

## Videos
>>Makes me think that a video, interacting with an interactive map, would be a good move.

And do you or I do the videos? Or can we make magic and then Joe Morris and Susan Cousineau make the videos? (When I was working at Autodesk and designing AutoCAD, I understood that my job was not to teach but to teach the teachers.)
 
## Meaning of Life
>> PS Perhaps a good intro document to some soil health context might be https://soilcarboncoalition.org/files/atlasbooklet.pdf

Wow! LOL! Yay!

Did you and your school bus ever do a Ken Kesey "One Flew Over The Cuckoo's Nest" thing while reading Penrose's "The Road to Reality" or something?

I look forward to double-clicking into this effort.

**Comment by managingwholes** [comment]
Thanks Theo, good responses.

# Numbers versus sticks

For simplicity, I would say that the crop insurance map need show only one data point: the $ value of indemnities for a county for a given year. (A breakdown by crop would be doable but quite complicated, and probably distract from a focus on soil health.) A popup could contain the values for that county for all years, in a chart. The political map has more data points, e.g. red and blue.

**Comment by theo-armour** [comment]
@managingwholes 

> A popup could contain the values for that county for all years, in a chart.

See yesterday's release for the chart in the popup!

https://theo-armour.github.io/maps-2021/sandbox/globe-us-county-indemnity/

> A breakdown by crop would be doable but quite complicated,... 

Hee hee! That's exactly the type of challenge that wants to be confronted. For example, could there be some pattern of crops that promulgates more claims that nobody has noticed before?

> and probably distract from a focus on soil health.

Got some soil health data that would be fun to show?
