### ISSUE TITLE
Good Sources of US Agricultural Data

### ISSUE THREAD

**Issue by theo-armour** [theo-armour/maps-2021#3]
@managingwholes 

I am looking for good, well-documented sources of agricultural data. A good first search item mught be the acreage of insured crop land for each US county. This data would tie in nicely to the US county insurance indemnity map I am currently working on,

 This site may may be a good source: https://quickstats.nass.usda.gov/

I entered the following parameters on this site and received what I think are good results

**Select Commodity**
* Program: Census
* Sector: Economics
* Group: Farms & Land Assets
* Commodity: Ag Land:
* Category: Area
* Data Item: Ag Land, Crop Insurance - Acres

**Select Location**
* County

**Select Time**
* 2017 ( or all )

Here are most of the parameters

![image](https://user-images.githubusercontent.com/547626/125894581-090250a4-2497-4302-9c73-f4e3b0d4f131.png)

Here are the first results:

![image](https://user-images.githubusercontent.com/547626/125894499-5aa01343-80ff-44ab-a9d5-7d0dd0dbf849.png)

What I would like to know

*I s this a good site to start to use as a resource
* Is that data I captured the best data to use to calculate indemnity per acre per county?
* Are there other data sets here that I should be investigating?

**Comment by managingwholes** [comment]
Hi Theo, sorry I've been occupied elsewhere for a bit. For cropland acres,
that looks like about the best available for cropland acres.

the following (
https://www.nass.usda.gov/Research_and_Science/Cropland/Release/index.php)
is too big a file for me to handle, but the National Cultivated Layer might
be usable somehow. I suspect it's some kind of arcgis file. Your find will
probably be better.

PS the popup charts you did look good. Would horizontal display, with time
on the x axis, with an index for years, be possible?

PPS I was going to update indeminities for 2018-2020 but the rma site is
down.

thanks much for your interest!

[image: image.png]

**Comment by theo-armour** [comment]
> the popup charts you did look good. Would horizontal display, with time
on the x axis, with an index for years, be possible?

I looked into horizontal charts - and will get there one day. One issue is usability on mobile devices. 

A horizontal chart will most likely need clipping to fit into many mobile devices. This means having the ability to click and to slide while in the same area. 

On a computer there is mouseover and mouseup. But on mobile there is only touch - and hovering over things to cause something to show is still beyond me. Therefore you have to touch to show. But then you can't use touching for sliding. 

[Of course the real dream is always to be able to display the data "inworld" with some kind of 3D graphic "augmented unreality"]


> PPS I was going to update indemnities for 2018-2020 but the rma site is
down.

Thank you for the update you sent. See the latest release for the results!
